language: python

sudo: false

install:
  - pip install tox

script:
  - tox

matrix:
  fast_finish: true
  include:
    - env: TOXENV=py35-dj111
      python: 3.5
    - env: TOXENV=py36-dj111
      python: 3.6
    - env: TOXENV=py35-dj20
      python: 3.5
    - env: TOXENV=py36-dj20
      python: 3.6
