language: python

sudo: false

install:
  - pip install tox

script:
  - tox

matrix:
  fast_finish: true
  include:
    - env: TOXENV=py27-dj18
      python: 2.7
    - env: TOXENV=py33-dj18
      python: 3.3
    - env: TOXENV=py34-dj18
      python: 3.4
    - env: TOXENV=py35-dj18
      python: 3.5
